apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  project: default
  source:
    repoURL: https://github.com/ivanklee86/argocd-tangle.git
    path: integration/kubernetes/example/manifests
    targetRevision: poc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
