argo-cd:
  configs:
    cm:
      accounts.automation: apiKey

    rbac:
      policy.csv: |
        p, role:tangle, applications, *, *, allow
        g, automation, role:tangle

    params:
      server.insecure: true
