argo-cd:
  configs:
    cm:
      accounts.automation: apiKey

    rbac:
      policy.csv: |
        p, role:tangle, projects, create, *, allow
        p, role:tangle, projects, get, *, allow
        p, role:tangle, projects, update, *, allow
        p, role:tangle, projects, delete, *, allow
        g, automation, role:tangle

    params:
      server.insecure: true
